using System.Globalization;
using System.Text;
using Atlas.Core.Models;

namespace Atlas.Core.Services;

/// <inheritdoc cref="IConfigGeneratorService"/>
public sealed class ConfigGeneratorService : IConfigGeneratorService
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public string GenerateServerCfg(ServerProfile p)
    {
        var sb = new StringBuilder();
        void L(string s = "") => sb.AppendLine(s);

        L("// ============================================================");
        L("// ATLAS Generated server.cfg");
        L($"// Profile: {p.Name}");
        L("// Regenerated by ATLAS on every write — manual edits will be lost.");
        L("// ============================================================");
        L();

        L("// --- Identity / access ---");
        L($"hostname = {Str(p.ServerName)};");
        L($"password = {Str(p.ServerPassword)};");
        L($"passwordAdmin = {Str(p.AdminPassword)};");
        L($"maxPlayers = {p.MaxPlayers};");
        L();

        L("// --- Message of the day ---");
        L($"motd[] = {ArrStr(p.MotdLines)};");
        L($"motdInterval = {p.MotdInterval};");
        L();

        L("// --- Logging ---");
        L($"logFile = {Str(p.LogFile)};");
        L($"timeStampFormat = {Str(p.TimeStampFormat ? "short" : "none")};");
        L();

        L("// --- Network ---");
        L($"maxPing = {p.MaxPing};");
        L($"maxDesync = {p.MaxDesync};");
        L($"maxPacketLoss = {p.MaxPacketLoss};");
        L($"MaxMsgSend = {p.MaxMsgSend};");
        L($"MaxSizeNonguaranteed = {p.MaxSizeNonguaranteed};");
        L($"MaxSizeGuaranteed = {p.MaxSizeGuaranteed};");
        L($"MinBandwidth = {p.MinBandwidth.ToString(Inv)};");
        L($"MaxBandwidth = {p.MaxBandwidth.ToString(Inv)};");
        L($"MinErrorToSend = {p.MinErrorToSend.ToString(Inv)};");
        L($"MinErrorToSendNear = {p.MinErrorToSendNear.ToString(Inv)};");
        L($"disconnectTimeout = {p.DisconnectTimeout};");
        L($"maxdisconnectTimeout = {p.MaxDisconnectTimeout};");
        if (p.Loopback) L("loopback = 1;");
        if (p.Upnp) L("upnp = 1;");   // server maps its own ports via a UPnP/IGD router
        L();

        L("// --- Security ---");
        L($"BattlEye = {B(p.EnableBattlEye)};");
        L($"verifySignatures = {p.VerifySignatures};");
        L($"kickDuplicate = {B(p.KickDuplicates)};");
        L($"requiredSecureId = {(p.RequiredSecureId ? 2 : 1)};");
        L($"allowedFilePatching = {(p.FilePatching ? 2 : 0)};   // 0 = none, 1 = headless only, 2 = all clients");
        L($"allowedLoadFileExtensions[] = {ArrStr(p.AllowedLoadFileExtensions)};");
        L($"allowedPreprocessFileExtensions[] = {ArrStr(p.AllowedPreprocessFileExtensions)};");
        L($"allowedHTMLLoadExtensions[] = {ArrStr(p.AllowedHTMLLoadExtensions)};");
        L($"allowedHTMLLoadURIs[] = {ArrStr(p.AllowedHTMLLoadURIs)};");
        L();

        if (p.UseHeadlessClients)
        {
            var ips = p.HeadlessClientIPs.Count > 0 ? p.HeadlessClientIPs : new List<string> { "127.0.0.1" };
            L("// --- Headless clients ---");
            L($"headlessClients[] = {ArrStr(ips)};");
            L($"localClient[] = {ArrStr(ips)};");
            L();
        }

        L("// --- Mission ---");
        if (!string.IsNullOrWhiteSpace(p.MissionName))
        {
            L("class Missions");
            L("{");
            L("    class Mission");
            L("    {");
            L($"        template = {Str(p.MissionName)};");
            L($"        difficulty = {Str(p.MissionDifficulty)};");
            L("    };");
            L("};");
        }
        else
        {
            L("// No mission template set — configure one on the Mission tab.");
        }
        L($"autoInit = {B(p.AutoInit)};");
        L($"persistent = {B(p.Persistent)};");
        L();

        L("// --- Voice over net ---");
        L($"disableVoN = {B(p.DisableVoN)};");
        L($"vonCodecQuality = {p.VonCodecQuality};");
        L();

        L("// --- Voting ---");
        // A threshold > 1.0 makes votes impossible to pass, which disables voting.
        var threshold = p.VotingEnabled ? p.VoteThreshold : 1.5f;
        L($"voteThreshold = {threshold.ToString(Inv)};");
        L($"voteMissionPlayers = {p.VoteMissionPlayers.ToString(Inv)};");
        L();

        L("// --- Misc ---");
        L($"drawingInMap = {B(p.DrawingInMap)};");
        L($"enableDebugConsole = {B(p.EnableDebugConsole)};");

        return sb.ToString();
    }

    public string GenerateBasicCfg(ServerProfile p)
    {
        var sb = new StringBuilder();
        void L(string s = "") => sb.AppendLine(s);

        L("// ============================================================");
        L("// ATLAS Generated basic.cfg");
        L($"// Profile: {p.Name}");
        L("// Network performance tuning. Regenerated by ATLAS on every write.");
        L("// ============================================================");
        L();
        L($"MaxMsgSend = {p.MaxMsgSend};");
        L($"MaxSizeGuaranteed = {p.MaxSizeGuaranteed};");
        L($"MaxSizeNonguaranteed = {p.MaxSizeNonguaranteed};");
        L($"MinBandwidth = {p.MinBandwidth.ToString(Inv)};");
        L($"MaxBandwidth = {p.MaxBandwidth.ToString(Inv)};");
        L($"MinErrorToSend = {p.MinErrorToSend.ToString(Inv)};");
        L($"MinErrorToSendNear = {p.MinErrorToSendNear.ToString(Inv)};");
        L();
        L("class sockets");
        L("{");
        L("    maxPacketSize = 1400;");
        L("};");

        return sb.ToString();
    }

    public string GenerateBeServerCfg(ServerProfile p)
    {
        // BattlEye config is a plain key/value file (no semicolons, no quotes).
        var sb = new StringBuilder();
        sb.AppendLine($"RConPassword {p.RconPassword}");
        sb.AppendLine($"RConPort {p.RconPort}");
        return sb.ToString();
    }

    public string BuildLaunchArguments(ServerProfile p)
    {
        var sb = new StringBuilder();
        var exe = !string.IsNullOrWhiteSpace(p.ServerExecutablePath)
            ? p.ServerExecutablePath
            : (p.UseProfilingBranch ? "arma3server_profiling_x64.exe" : "arma3server_x64.exe");
        sb.Append(Quote(exe));

        void Flag(string f) => sb.Append(' ').Append(f);

        Flag($"-port={p.Port}");
        if (!string.IsNullOrWhiteSpace(p.ArmaProfileName)) Flag($"-name={MaybeQuote(p.ArmaProfileName)}");
        Flag("-config=server.cfg");
        Flag("-cfg=basic.cfg");

        // Resolve the mod list in load order. Server-only mods go in -serverMod=, the rest in -mod=.
        var ordered = p.Mods.OrderBy(m => m.LoadOrder).ToList();
        var regular = string.Join(";", ordered
            .Where(m => m.EnabledForServer && !m.IsServerOnly)
            .Select(ModFolder).Where(s => s.Length > 0));
        var serverOnly = string.Join(";", ordered
            .Where(m => m.EnabledForServer && m.IsServerOnly)
            .Select(ModFolder).Where(s => s.Length > 0));
        if (regular.Length > 0) Flag($"-mod={MaybeQuote(regular)}");
        if (serverOnly.Length > 0) Flag($"-serverMod={MaybeQuote(serverOnly)}");

        Flag(p.EnableBattlEye ? "-BattlEye" : "-noBattlEye");
        if (p.FilePatching) Flag("-filePatching");
        if (p.NetLog) Flag("-netlog");
        if (p.NoSound) Flag("-nosound");
        if (p.NoSplash) Flag("-nosplash");
        if (p.SkipIntro) Flag("-skipIntro");
        if (p.WorldEmpty) Flag("-world=empty");
        if (p.NoPause) Flag("-noPause");
        if (p.NoLogs) Flag("-nologs");
        if (p.LoadMissionToMemory) Flag("-loadMissionToMemory");
        if (p.CpuCount > 0) Flag($"-cpuCount={p.CpuCount}");
        if (p.ExThreads > 0) Flag($"-exThreads={p.ExThreads}");
        if (p.MaxMem > 0) Flag($"-maxMem={p.MaxMem}");
        if (p.EnableHT) Flag("-enableHT");
        if (p.HugePages) Flag("-hugePages");
        if (!string.IsNullOrWhiteSpace(p.Malloc)) Flag($"-malloc={p.Malloc}");
        if (p.BandwidthAlg > 0) Flag($"-bandwidthAlg={p.BandwidthAlg}");
        if (p.LimitFPS > 0) Flag($"-limitFPS={p.LimitFPS}");
        if (p.RankingEnabled && !string.IsNullOrWhiteSpace(p.RankingFile)) Flag($"-ranking={MaybeQuote(p.RankingFile)}");
        if (!string.IsNullOrWhiteSpace(p.CustomLaunchParameters)) sb.Append(' ').Append(p.CustomLaunchParameters.Trim());

        return sb.ToString();
    }

    public async Task WriteAllConfigFilesAsync(ServerProfile p, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(p.ServerDirectory))
            throw new InvalidOperationException(
                "The profile's server directory is not set. Set it on the Performance tab before writing config files.");

        Directory.CreateDirectory(p.ServerDirectory);
        await File.WriteAllTextAsync(Path.Combine(p.ServerDirectory, "server.cfg"), GenerateServerCfg(p), ct)
            .ConfigureAwait(false);
        await File.WriteAllTextAsync(Path.Combine(p.ServerDirectory, "basic.cfg"), GenerateBasicCfg(p), ct)
            .ConfigureAwait(false);

        var beDir = Path.Combine(p.ServerDirectory, "BattlEye");
        Directory.CreateDirectory(beDir);
        await File.WriteAllTextAsync(Path.Combine(beDir, "beserver_x64.cfg"), GenerateBeServerCfg(p), ct)
            .ConfigureAwait(false);
    }

    // ---- helpers ----

    /// <summary>Quotes and escapes a value as an Arma config string literal (internal quotes are doubled).</summary>
    private static string Str(string? s) => "\"" + (s ?? string.Empty).Replace("\"", "\"\"") + "\"";

    /// <summary>Renders a list as an Arma string array, e.g. <c>{"a", "b"}</c>.</summary>
    private static string ArrStr(IEnumerable<string> items) => "{" + string.Join(", ", items.Select(Str)) + "}";

    /// <summary>Boolean as an Arma config flag (1/0).</summary>
    private static string B(bool b) => b ? "1" : "0";

    private static string ModFolder(ArmaModEntry m)
    {
        if (!string.IsNullOrWhiteSpace(m.FolderName)) return m.FolderName;
        if (!string.IsNullOrWhiteSpace(m.Name)) return "@" + m.Name;
        return string.Empty;
    }

    // Windows paths cannot contain double-quotes; strip any defensively so a stray quote can't break the arg.
    private static string Quote(string s) => "\"" + s.Replace("\"", string.Empty) + "\"";

    private static string MaybeQuote(string s) => s.Contains(' ') ? Quote(s) : s;
}
