using System.Globalization;
using System.Text;
using Atlas.Core.Models;

namespace Atlas.Core.Services;

/// <inheritdoc cref="IConfigGeneratorService"/>
public sealed class ConfigGeneratorService : IConfigGeneratorService
{
    private static readonly CultureInfo Inv = CultureInfo.InvariantCulture;

    public string GenerateServerCfg(ServerProfile p)
    {
        var sb = new StringBuilder();
        void L(string s = "") => sb.AppendLine(s);

        L("// ============================================================");
        L("// ATLAS Generated server.cfg");
        L($"// Profile: {p.Name}");
        L("// Regenerated by ATLAS on every write — manual edits will be lost.");
        L("// ============================================================");
        L();

        L("// --- Identity / access ---");
        L($"hostname = {Str(p.ServerName)};");
        L($"password = {Str(p.ServerPassword)};");
        L($"passwordAdmin = {Str(p.AdminPassword)};");
        var adminUids = SplitList(p.AdminUids);
        if (adminUids.Length > 0)
            L($"admins[] = {ArrStr(adminUids)};   // whitelisted UIDs: #login without a password");
        L($"maxPlayers = {p.MaxPlayers};");
        L();

        L("// --- Message of the day ---");
        L($"motd[] = {ArrStr(p.MotdLines)};");
        L($"motdInterval = {p.MotdInterval};");
        L();

        L("// --- Logging ---");
        L($"logFile = {Str(p.LogFile)};");
        L($"timeStampFormat = {Str(p.TimeStampFormat ? "short" : "none")};");
        L();

        L("// --- Network ---");
        L($"maxPing = {p.MaxPing};");
        L($"maxDesync = {p.MaxDesync};");
        L($"maxPacketLoss = {p.MaxPacketLoss};");
        // MaxMsgSend / MaxSize* / Min-MaxBandwidth / MinErrorToSend* are basic.cfg keys (emitted in
        // GenerateBasicCfg and honored via -cfg=basic.cfg) — not duplicated here to avoid divergent copies.
        L($"disconnectTimeout = {p.DisconnectTimeout};");
        L($"maxdisconnectTimeout = {p.MaxDisconnectTimeout};");
        if (p.MaxCustomFileSize > 0) L($"MaxCustomFileSize = {p.MaxCustomFileSize};");
        if (p.Loopback) L("loopback = 1;");
        if (p.Upnp) L("upnp = 1;");   // server maps its own ports via a UPnP/IGD router
        L();

        L("// --- Security ---");
        L($"BattlEye = {B(p.EnableBattlEye)};");
        L($"verifySignatures = {p.VerifySignatures};");
        L($"kickDuplicate = {B(p.KickDuplicates)};");
        L($"requiredSecureId = {(p.RequiredSecureId ? 2 : 1)};");
        if (p.RequiredBuild > 0) L($"requiredBuild = {p.RequiredBuild};");
        L($"allowedFilePatching = {p.FilePatching};   // 0 = none, 1 = headless only, 2 = all clients");
        L($"allowedLoadFileExtensions[] = {ArrStr(p.AllowedLoadFileExtensions)};");
        L($"allowedPreprocessFileExtensions[] = {ArrStr(p.AllowedPreprocessFileExtensions)};");
        L($"allowedHTMLLoadExtensions[] = {ArrStr(p.AllowedHTMLLoadExtensions)};");
        L($"allowedHTMLLoadURIs[] = {ArrStr(p.AllowedHTMLLoadURIs)};");
        L();

        if (p.UseHeadlessClients)
        {
            var ips = p.HeadlessClientIPs.Count > 0 ? p.HeadlessClientIPs : new List<string> { "127.0.0.1" };
            L("// --- Headless clients ---");
            L($"headlessClients[] = {ArrStr(ips)};");
            L($"localClient[] = {ArrStr(ips)};");
            L();
        }

        L("// --- Mission ---");
        var missionQueue = MissionQueueList(p);
        if (missionQueue.Length > 0)
        {
            L("class Missions");
            L("{");
            for (var i = 0; i < missionQueue.Length; i++)
            {
                L($"    class Mission_{i}");
                L("    {");
                L($"        template = {Str(missionQueue[i])};");
                L($"        difficulty = {Str(p.MissionDifficulty)};");
                if (p.SkipLobby) L("        skipLobby = 1;");
                L("    };");
            }
            L("};");
        }
        else
        {
            L("// No mission template set — configure one on the Mission tab.");
        }
        // autoInit is a STARTUP PARAMETER (-autoInit, emitted in BuildLaunchArguments) — NOT a server.cfg
        // key; writing it here did nothing (Arma ignores unknown cfg keys). What server.cfg needs is
        // persistent = 1, without which Arma skips -autoInit entirely — so force it on with autoInit.
        var persistent = p.Persistent || p.AutoInit;
        L($"persistent = {B(persistent)};");
        if (p.AutoSelectMission) L("autoSelectMission = 1;");
        if (p.RandomMissionOrder) L("randomMissionOrder = 1;");
        if (p.MissionWhitelistEnabled)
        {
            // Union of the checked rotation missions and the profile's extra entries: an admin can only
            // #mission-change to whitelisted missions, so the rotation itself must always be included.
            var whitelist = missionQueue
                .Concat(SplitList(p.MissionWhitelistExtra))
                .Distinct(StringComparer.OrdinalIgnoreCase)
                .ToArray();
            if (whitelist.Length > 0)
                L($"missionWhitelist[] = {ArrStr(whitelist)};   // limits admin #mission changes");
        }
        L();

        L("// --- Voice over net ---");
        L($"disableVoN = {B(p.DisableVoN)};");
        L($"vonCodecQuality = {p.VonCodecQuality};");
        L($"vonCodec = {(p.VonCodecLegacy ? 0 : 1)};");
        L();

        L("// --- Voting ---");
        // A threshold > 1.0 makes votes impossible to pass, which disables voting.
        var threshold = p.VotingEnabled ? p.VoteThreshold : 1.5f;
        L($"voteThreshold = {threshold.ToString(Inv)};");
        L($"voteMissionPlayers = {(int)Math.Round(p.VoteMissionPlayers)};");
        L();

        // Behaviour timeouts / idle throttle — 0 = omit (Arma defaults apply).
        if (p.LobbyIdleTimeout > 0 || p.RoleTimeOut > 0 || p.IdleFPSLimit > 0)
        {
            L("// --- Timeouts / idle ---");
            if (p.LobbyIdleTimeout > 0) L($"lobbyIdleTimeout = {p.LobbyIdleTimeout};");
            if (p.RoleTimeOut > 0) L($"roleTimeOut = {p.RoleTimeOut};");
            if (p.IdleFPSLimit > 0)
                L($"idleFPSLimit = {Math.Clamp(p.IdleFPSLimit, 5, 60)};   // FPS cap only while 0 players are connected");
            L();
        }

        if (p.AntiFloodEnabled)
        {
            L("// --- Anti-flood (chat/command spam protection) ---");
            L("class AntiFlood");
            L("{");
            L($"    cycleTime = {p.AntiFloodCycleTime.ToString(Inv)};");
            L($"    cycleLimit = {p.AntiFloodCycleLimit};");
            L($"    cycleHardLimit = {p.AntiFloodCycleHardLimit};");
            L($"    enableKick = {B(p.AntiFloodKick)};");
            L("};");
            L();
        }

        // Scripting callbacks — only emit the advanced hooks that are set.
        if (!string.IsNullOrWhiteSpace(p.ServerCommandPassword) || !string.IsNullOrWhiteSpace(p.OnUserConnected)
            || !string.IsNullOrWhiteSpace(p.OnUserDisconnected) || !string.IsNullOrWhiteSpace(p.OnHackedData)
            || !string.IsNullOrWhiteSpace(p.OnDifferentData) || !string.IsNullOrWhiteSpace(p.OnUnsignedData)
            || !string.IsNullOrWhiteSpace(p.OnUserKicked))
        {
            L("// --- Scripting callbacks ---");
            if (!string.IsNullOrWhiteSpace(p.ServerCommandPassword)) L($"serverCommandPassword = {Str(p.ServerCommandPassword)};");
            if (!string.IsNullOrWhiteSpace(p.OnUserConnected)) L($"onUserConnected = {Str(p.OnUserConnected)};");
            if (!string.IsNullOrWhiteSpace(p.OnUserDisconnected)) L($"onUserDisconnected = {Str(p.OnUserDisconnected)};");
            if (!string.IsNullOrWhiteSpace(p.OnHackedData)) L($"onHackedData = {Str(p.OnHackedData)};");
            if (!string.IsNullOrWhiteSpace(p.OnDifferentData)) L($"onDifferentData = {Str(p.OnDifferentData)};");
            if (!string.IsNullOrWhiteSpace(p.OnUnsignedData)) L($"onUnsignedData = {Str(p.OnUnsignedData)};");
            if (!string.IsNullOrWhiteSpace(p.OnUserKicked)) L($"onUserKicked = {Str(p.OnUserKicked)};");
            L();
        }

        L("// --- Misc ---");
        L($"drawingInMap = {B(p.DrawingInMap)};");
        L($"enableDebugConsole = {B(p.EnableDebugConsole)};");

        return sb.ToString();
    }

    public string GenerateBasicCfg(ServerProfile p)
    {
        var sb = new StringBuilder();
        void L(string s = "") => sb.AppendLine(s);

        L("// ============================================================");
        L("// ATLAS Generated basic.cfg");
        L($"// Profile: {p.Name}");
        L("// Network performance tuning. Regenerated by ATLAS on every write.");
        L("// ============================================================");
        L();
        L($"MaxMsgSend = {p.MaxMsgSend};");
        L($"MaxSizeGuaranteed = {p.MaxSizeGuaranteed};");
        L($"MaxSizeNonguaranteed = {p.MaxSizeNonguaranteed};");
        L($"MinBandwidth = {p.MinBandwidth.ToString(Inv)};");
        L($"MaxBandwidth = {p.MaxBandwidth.ToString(Inv)};");
        L($"MinErrorToSend = {p.MinErrorToSend.ToString(Inv)};");
        L($"MinErrorToSendNear = {p.MinErrorToSendNear.ToString(Inv)};");
        L();
        L("class sockets");
        L("{");
        L($"    maxPacketSize = {p.MaxPacketSize};");
        L("};");

        return sb.ToString();
    }

    public string GenerateBeServerCfg(ServerProfile p)
    {
        // BattlEye config is a plain key/value file (no semicolons, no quotes).
        var sb = new StringBuilder();
        sb.AppendLine($"RConPassword {p.RconPassword}");
        sb.AppendLine($"RConPort {p.RconPort}");
        return sb.ToString();
    }

    public string GenerateArma3Profile(ServerProfile p)
    {
        var sb = new StringBuilder();
        void L(string s = "") => sb.AppendLine(s);

        L("// ATLAS-generated server profile — granular difficulty, AI level and view distance.");
        L("// The server.cfg mission must use difficulty = \"Custom\" for this CustomDifficulty to apply.");
        L("version=1;");
        L("class DifficultyPresets");
        L("{");
        L("\tclass CustomDifficulty");
        L("\t{");
        L("\t\tclass Options");
        L("\t\t{");
        L($"\t\t\tgroupIndicators={p.DiffGroupIndicators};");
        L($"\t\t\tfriendlyTags={p.DiffFriendlyTags};");
        L($"\t\t\tenemyTags={p.DiffEnemyTags};");
        L($"\t\t\tdetectedMines={p.DiffDetectedMines};");
        L($"\t\t\tcommands={p.DiffCommands};");
        L($"\t\t\twaypoints={p.DiffWaypoints};");
        L($"\t\t\tweaponInfo={p.DiffWeaponInfo};");
        L($"\t\t\tstanceIndicator={p.DiffStanceIndicator};");
        L($"\t\t\treducedDamage={B(p.DiffReducedDamage)};");
        L($"\t\t\tstaminaBar={B(p.DiffStaminaBar)};");
        L($"\t\t\tweaponCrosshair={B(p.DiffWeaponCrosshair)};");
        L($"\t\t\tvisionAid={B(p.DiffVisionAid)};");
        L($"\t\t\tthirdPersonView={p.DiffThirdPersonView};");
        L($"\t\t\tcameraShake={B(p.DiffCameraShake)};");
        L($"\t\t\tscoreTable={B(p.DiffScoreTable)};");
        L($"\t\t\tdeathMessages={B(p.DiffDeathMessages)};");
        L($"\t\t\tvonID={B(p.DiffVonID)};");
        L($"\t\t\tmapContentFriendly={B(p.DiffMapContentFriendly)};");
        L($"\t\t\tmapContentEnemy={B(p.DiffMapContentEnemy)};");
        L($"\t\t\tmapContentMines={B(p.DiffMapContentMines)};");
        L($"\t\t\tautoReport={B(p.DiffAutoReport)};");
        L($"\t\t\tmultipleSaves={B(p.DiffMultipleSaves)};");
        L($"\t\t\ttacticalPing={B(p.DiffTacticalPing)};");
        L("\t\t};");
        L("\t\taiLevelPreset=\"AILevelCustom\";");
        L("\t};");
        L("\tclass CustomAILevel");
        L("\t{");
        L($"\t\tskillAI={p.SkillAI.ToString(Inv)};");
        L($"\t\tprecisionAI={p.PrecisionAI.ToString(Inv)};");
        L("\t};");
        L("};");
        if (p.ViewDistance > 0) L($"viewDistance={p.ViewDistance};");
        if (p.ObjectViewDistance > 0) L($"preferredObjectViewDistance={p.ObjectViewDistance};");
        if (p.TerrainGrid > 0) L($"terrainGrid={p.TerrainGrid.ToString(Inv)};");

        return sb.ToString();
    }

    public string BuildLaunchArguments(ServerProfile p)
    {
        var sb = new StringBuilder();
        var exe = !string.IsNullOrWhiteSpace(p.ServerExecutablePath)
            ? p.ServerExecutablePath
            : (p.UseProfilingBranch ? "arma3server_profiling_x64.exe" : "arma3server_x64.exe");
        sb.Append(Quote(exe));

        void Flag(string f) => sb.Append(' ').Append(f);

        Flag($"-port={p.Port}");
        if (!string.IsNullOrWhiteSpace(p.ArmaProfileName)) Flag($"-name={MaybeQuote(p.ArmaProfileName)}");
        Flag("-config=server.cfg");
        Flag("-cfg=basic.cfg");

        // Resolve the mod list in load order. Server-only mods go in -serverMod=, the rest in -mod=.
        // Enabled creator/platform DLC folders lead the client-facing -mod= list.
        var ordered = p.Mods.OrderBy(m => m.LoadOrder).ToList();
        var regular = string.Join(";", EnabledDlcFolders(p)
            .Concat(ordered.Where(m => m.EnabledForServer && !m.IsServerOnly).Select(ModFolder))
            .Where(s => s.Length > 0));
        var serverOnly = string.Join(";", ordered
            .Where(m => m.EnabledForServer && m.IsServerOnly)
            .Select(ModFolder).Where(s => s.Length > 0));
        if (regular.Length > 0) Flag($"-mod={MaybeQuote(regular)}");
        if (serverOnly.Length > 0) Flag($"-serverMod={MaybeQuote(serverOnly)}");

        Flag(p.EnableBattlEye ? "-BattlEye" : "-noBattlEye");
        if (p.ServerFilePatching) Flag("-filePatching");
        if (p.NetLog) Flag("-netlog");
        if (p.NoSound) Flag("-nosound");
        if (p.NoSplash) Flag("-nosplash");
        if (p.SkipIntro) Flag("-skipIntro");
        if (p.WorldEmpty) Flag("-world=empty");
        if (p.NoPause) Flag("-noPause");
        if (p.NoLogs) Flag("-nologs");
        if (p.LoadMissionToMemory) Flag("-loadMissionToMemory");
        if (p.AutoInit) Flag("-autoInit");   // startup param, not a cfg key; needs persistent=1 (forced in server.cfg)
        if (p.CpuCount > 0) Flag($"-cpuCount={p.CpuCount}");
        if (p.ExThreads > 0) Flag($"-exThreads={p.ExThreads}");
        if (p.MaxMem > 0) Flag($"-maxMem={p.MaxMem}");
        if (p.EnableHT) Flag("-enableHT");
        if (p.HugePages) Flag("-hugePages");
        if (!string.IsNullOrWhiteSpace(p.Malloc)) Flag($"-malloc={p.Malloc}");
        if (p.BandwidthAlg > 0) Flag($"-bandwidthAlg={p.BandwidthAlg}");
        if (p.LimitFPS > 0) Flag($"-limitFPS={p.LimitFPS}");
        if (p.RankingEnabled && !string.IsNullOrWhiteSpace(p.RankingFile)) Flag($"-ranking={MaybeQuote(p.RankingFile)}");
        if (!string.IsNullOrWhiteSpace(p.CustomLaunchParameters)) sb.Append(' ').Append(p.CustomLaunchParameters.Trim());

        return sb.ToString();
    }

    public async Task WriteAllConfigFilesAsync(ServerProfile p, CancellationToken ct = default)
    {
        if (string.IsNullOrWhiteSpace(p.ServerDirectory))
            throw new InvalidOperationException(
                "The profile's server directory is not set. Set it on the Performance tab before writing config files.");

        Directory.CreateDirectory(p.ServerDirectory);
        await File.WriteAllTextAsync(Path.Combine(p.ServerDirectory, "server.cfg"), GenerateServerCfg(p), ct)
            .ConfigureAwait(false);
        await File.WriteAllTextAsync(Path.Combine(p.ServerDirectory, "basic.cfg"), GenerateBasicCfg(p), ct)
            .ConfigureAwait(false);

        var beDir = Path.Combine(p.ServerDirectory, "BattlEye");
        Directory.CreateDirectory(beDir);
        await File.WriteAllTextAsync(Path.Combine(beDir, "beserver_x64.cfg"), GenerateBeServerCfg(p), ct)
            .ConfigureAwait(false);

        // Arma3Profile — written where the server reads it given ATLAS's launch line
        // (-profiles=<ServerDir>\profiles -name=<name>): <ServerDir>\profiles\Users\<name>\<name>.Arma3Profile.
        var profileName = string.IsNullOrWhiteSpace(p.ArmaProfileName) ? "ATLAS" : p.ArmaProfileName.Trim();
        var profileDir = Path.Combine(p.ServerDirectory, "profiles", "Users", profileName);
        Directory.CreateDirectory(profileDir);
        await File.WriteAllTextAsync(Path.Combine(profileDir, profileName + ".Arma3Profile"), GenerateArma3Profile(p), ct)
            .ConfigureAwait(false);
    }

    // ---- helpers ----

    /// <summary>Quotes and escapes a value as an Arma config string literal (internal quotes are doubled).</summary>
    private static string Str(string? s) => "\"" + (s ?? string.Empty).Replace("\"", "\"\"") + "\"";

    /// <summary>Renders a list as an Arma string array, e.g. <c>{"a", "b"}</c>.</summary>
    private static string ArrStr(IEnumerable<string> items) => "{" + string.Join(", ", items.Select(Str)) + "}";

    /// <summary>Boolean as an Arma config flag (1/0).</summary>
    private static string B(bool b) => b ? "1" : "0";

    /// <summary>Splits a user-entered list (newline and/or ';' separated) into trimmed non-empty items.</summary>
    private static string[] SplitList(string? s) =>
        (s ?? string.Empty).Split(new[] { ';', '\r', '\n' },
            StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);

    /// <summary>The ordered mission rotation: the ';'-separated <see cref="ServerProfile.MissionQueue"/>, or the
    /// single <see cref="ServerProfile.MissionName"/> when the queue is empty (legacy / manual entry).</summary>
    private static string[] MissionQueueList(ServerProfile p)
    {
        var arr = (p.MissionQueue ?? string.Empty)
            .Split(';', StringSplitOptions.RemoveEmptyEntries | StringSplitOptions.TrimEntries);
        if (arr.Length == 0 && !string.IsNullOrWhiteSpace(p.MissionName))
            return new[] { p.MissionName.Trim() };
        return arr;
    }

    private static string ModFolder(ArmaModEntry m)
    {
        if (!string.IsNullOrWhiteSpace(m.FolderName)) return m.FolderName;
        if (!string.IsNullOrWhiteSpace(m.Name)) return "@" + m.Name;
        return string.Empty;
    }

    /// <summary>The Arma root folder names for the enabled creator/platform DLC, in a stable order.</summary>
    internal static IEnumerable<string> EnabledDlcFolders(ServerProfile p)
    {
        if (p.DlcContact) yield return "Contact";
        if (p.DlcGlobalMobilization) yield return "gm";
        if (p.DlcPrairieFire) yield return "vn";
        if (p.DlcCsla) yield return "csla";
        if (p.DlcWesternSahara) yield return "ws";
        if (p.DlcSpearhead1944) yield return "spe";
        if (p.DlcReactionForces) yield return "rf";
        if (p.DlcExpeditionaryForces) yield return "ef";
    }

    // Windows paths cannot contain double-quotes; strip any defensively so a stray quote can't break the arg.
    private static string Quote(string s) => "\"" + s.Replace("\"", string.Empty) + "\"";

    private static string MaybeQuote(string s) => s.Contains(' ') ? Quote(s) : s;
}
